### PR TITLE
Ensure correct functionality on Debian systems

### PR DESCRIPTION
**Pull request by janvonde**
Running sensors-detect on Debian Jessie it stores the modules and comment in /etc/modules and not /etc/modprobe.d/lm_sensors.conf. This pull request reflects this issue and fixes it. Would be nice if you could merge it and publish as an update on puppetforge

### CODE REVIEW

**Comment by djjudas21** [comment]
Thanks for the patch. This will improve the module but it still won't work properly on Debian etc.

The `exec` in this module calls `sensors-detect < /dev/null` which just accepts all the defaults. On Red Hat, the default is to write out the config at the end - on Debian, the default is to _not_ write out the config. So you end up without lines being appended to `/etc/modules`

I'm not sure what to do about this - I'm a Red Hat guy, and while I do have Debian and Ubuntu VMs for testing, you obviously can't run `sensors-detect` on a VM because it doesn't have hardware sensors.

**Comment by janvonde** [comment]
What we could try is something like

```
yes "yes" | sensors-detect
```

I did a quick test and this worked. It has the side effect, that it assumes yes to the default "no" questions as well. This makes the initial run much longer though. What do you think about this? I could change my pull request to this?

**Comment by djjudas21** [comment]
That seems OK, except the warnings in `sensors-detect` say that _some_ of the checks can cause system instability etc. It's probably fine 99% of the time but I would be nervous about crashing someone's live server!

Maybe we could use this approach but use `yes "yes" | sensors-detect` only for Debian, by using a selector inside the `exec`. Little bit messy, but at least it will contain the side effect only to Debian systems, and not affect Red Hat.

**Comment by janvonde** [comment]
Sure, I ment updating it for Debian only as well. I will update the pull request later today :-)

**Comment by djjudas21** [comment]
Cool, thanks. I don't have a way of testing it on a Debian/Ubuntu hardware system, so I will trust you that it works! I'll make a new release to Puppet Forge too.

**Comment by janvonde** [comment]
I will test it on my server. I ran into the problem yesterday, this is why I tried to fix it, but you are right, I did a manual run before. I show my tests later here.

**Comment by djjudas21** [comment]
I think we need to do 2 tests:
- Delete your existing sensors config, and run Puppet to to ensure this module runs `sensors-detect` and generates the config
- Run Puppet again to ensure this module does _not_ run `sensors-detect` again

**Comment by janvonde** [comment]
I updated the pull request as discussed. My test was successful. 

I had no entries in /etc/modules before I made the first run:

```
root@hs ~ # cat /etc/modules
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
```

I ran puppet and the command was executed:

```
root@hs ~ # puppet agent --test --server puppet.example.net
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for hs.fritz.box
Info: Applying configuration version '1436933615'
Notice: /Stage[main]/Lm_sensors/Exec[sensors-detect]/returns: executed successfully
Info: /Stage[main]/Lm_sensors/Exec[sensors-detect]: Scheduling refresh of Service[lm_sensors]
Notice: /Stage[main]/Lm_sensors/Service[lm_sensors]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 35.55 seconds
```

Afterwards I checked /etc/modules and the lines were added:

```
root@hs ~ # cat /etc/modules
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.



# Generated by sensors-detect on Wed Jul 15 06:13:53 2015
# Chip drivers
adt7475
coretemp
```

Another run of the agent didn't execute the sensors-detect command again:

```
root@hs ~ # puppet agent --test --server puppet.example.net
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for hs.fritz.box
Info: Applying configuration version '1436933615'
Notice: Finished catalog run in 33.71 seconds
root@hs ~ # 
```

**Comment by djjudas21** [comment]
Thanks for your work. I will roll a new release today.

**Comment by djjudas21** [comment]
One more question - which versions(s) of Debian did you test this on? I want to fill in the OS compatibility metadata.

**Comment by janvonde** [comment]
jessie

**Comment by djjudas21** [comment]
Thanks - now uploaded 0.2.0 to the Forge

**Comment by djjudas21** [comment]
... and release 0.2.1

**Pull request merged**
