### PR TITLE
Add support for modifying chipset parameters

### PR DESCRIPTION
**Pull request by monotek**
Refactored the module to accept parameters and modify chip parameters via:

```
    lm_sensors::chipset { 'nct6776-isa-0290':
      ensure => present,
      chip_configs => ['ignore in1', 'label temp3 "SYS Temp"', 'compute temp3 @-20,@-20'],
    }
```

### CODE REVIEW

**Comment by djjudas21** [comment]
Awesome, thanks. What platforms/distros have you tested this on?

**Comment by monotek** [comment]
Currently on Debian 7, Ubuntu 12.04, 16.04 & Centos 7.3.

**Comment by djjudas21** [comment]
Great, that's very comprehensive. Have merged this and will tag a new release.

**Comment by djjudas21** [comment]
Sorry I took so long - I've just tagged `0.3.0` and released on Puppet Forge too. Thanks for your work!

**Pull request merged**
